/**
 * Gemini-Only Prompt Creator
 * Sprint 3: All prompt generation is done by Gemini, regardless of target model.
 * This ensures consistent, ModelSpec-aware prompt generation.
 */

export type PromptGenerator = 'gemini-fallback';

/**
 * Returns the prompt generator strategy (always Gemini for Sprint 3)
 * 
 * @returns Always 'gemini-fallback' - all prompts are generated by Gemini
 */
export function resolvePromptGenerator(): PromptGenerator {
  return 'gemini-fallback';
}
